name: Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '18.x'
      - run: yarn
      - run: |
          git config --global user.email $BOT_EMAIL
          git config --global user.name rambler-ui-bot
        env:
          BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
      - run: |
          echo "@rambler-tech:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn build
      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '18.x'
      - run: yarn
      - run: yarn docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
